var Big=Big||{};Big.Browse=Big.Catalog||{};Big.Browse.Slider={init:function(){$('.flexslider').flexslider({animation:"fade"});}}
Big.Browse.SideNavOpnClose={init:function(){var SideNav=$('.prdct-attrbs h4');$(SideNav).bind("click",function(){if($(this).parent().hasClass("opnd")){$(this).parent().addClass("clsd");$(this).parent().removeClass("opnd");}else{$(this).parent().addClass("opnd");$(this).parent().removeClass("clsd");}})}}
Big.Browse.MoreLess={init:function(){$('.prdct-attrbs ul').each(function(){$(this).children('li:gt(4)').hide();});$(".prdct-attrbs .moreLess").live('click',function(e){e.preventDefault();var type=$(this).attr("data-type");$(this).parents(".prdct-attrbs").find("ul").children('li:gt(4)').slideToggle('fast');if(type=="more"){$(this).attr("data-type","less");$(this).html("Show Less");}else{$(this).attr("data-type","more");$(this).html("Show More");}});}}
Big.Browse.SizePicker={init:function(){$("#productDetailSize").live('change',function(){var parentModal=$(this).closest('.modal-wrpr');var colorswathclick=$(parentModal).find(".clr-swtch").parent("li.actv");var color=$(colorswathclick).find('a').attr('rel');var prodId=$(colorswathclick).find('a').attr('data-prodid');var size=$(this).val();$(parentModal).find("p.pdp-skun-style").removeClass("dNone");var result=Big.Browse.ColorSizePicker.ajaxCallBack(color,size,prodId,'');$(parentModal).find("#skuIdHolder").text(result.skuId);$(parentModal).find(".sizeError").text("");$(parentModal).find("#getSkuId").val(result.skuId);$(parentModal).find(".fstorebtn").attr('data-skuid',result.skuId);$(parentModal).find(".fstorebtn").attr('data-style',result.skuStyle);$(parentModal).find(".findinstorea").attr('data-skuid',result.skuId);$(parentModal).find(".findinstorea").attr('data-style',result.skuStyle);$(parentModal).find("#skuStyleHolder").text(result.skuStyle);$(parentModal).find("#skuIdHolderWishlist").attr('value',result.skuId);$(parentModal).find("#skuIdWishlistItemId").attr('value',result.skuId);$(parentModal).find(".guestAddWishlist").attr('data-skuid',result.skuId);$(parentModal).find(".pdp-skun-style").removeClass("dNone");var priceObject=$(parentModal).find('div.priceHolder');var resultPrice=result.price;var priceData=resultPrice["price-data"];priceObject.html(function(){return $("<p/>").html(priceData).text();});if(resultPrice["save-price"]!=null){priceObject.append(function(){return $($("<p/>").html(resultPrice["save-price"]).text())});}
if(resultPrice["sale-end"]!=null){$(".slends").remove();priceObject.append(function(){return $($("<p/>").html(resultPrice["sale-end"]).text());});}
var badgeHolder=$(parentModal).find("div.badges");var badgeUrl=result.badgeType;if(badgeUrl!=""){$(badgeHolder).html(function(){return $("<img />").attr('src',badgeUrl);});}else{if(badgeUrl=="")
$(badgeHolder).html(" ");}
$(parentModal).find("#selectedClourHolder").text(result.slectedColour);$(".qtyRemain").val(result.remainingQty);$(parentModal).find("#remainingqtyholder").text("");var callToPrice=result.callForPrice;if(callToPrice=="false"){$('.cal-ord').addClass('dNone');$(parentModal).find('.storeOnly').addClass('dNone');$(parentModal).find('.ajaxAddToCart').removeClass("dNone");$('.ajaxAddToCart').removeClass("greyColor");if(!$(parentModal).find('.fstorebtn').hasClass('noLinks')){$(parentModal).find('.fstoreLink').removeClass("dNone");$(parentModal).find('.fstorebtn').addClass('dNone');}
if(result.remainingQty<=0){$('.ajaxAddToCart').addClass("greyColor")
$(".ajaxAddToCart").attr('disabled',true);$(".ajaxAddToCart").val('Out of Stock');}else{$('.ajaxAddToCart').removeClass("greyColor")
$(".ajaxAddToCart").attr('disabled',false);$(".ajaxAddToCart").val('ADD TO CART');}}else{$(parentModal).find('.fstoreLink').addClass("dNone");$(parentModal).find('.fstorebtn').removeClass('dNone');$('.ajaxAddToCart').addClass("dNone");$('.cal-ord').removeClass('dNone');$(parentModal).find('.storeOnly').removeClass('dNone');$(parentModal).find(".storeOnly").text("Available In Store Only");}
$(parentModal).find(".pdp-mn-thumbs ul").html("");var cList=$(parentModal).find('.pdp-mn-thumbs ul');var ImagesArray=result.Images;if(ImagesArray.length>0)
{var mainImage=ImagesArray[0].largeImage;var regularImage=ImagesArray[0].regularImage;$(parentModal).find("#productImg").prop('src',regularImage);$(parentModal).find(".pdp-mn-img").attr("data-image",mainImage);$.each(ImagesArray,function(index,image){var li=$('<li/>').attr('data-large-image',image.largeImage).attr('data-regular-image',image.regularImage).appendTo(cList);var aaa=$('<a/>').attr("href","#").appendTo(li);var img=$('<img/>').attr("src",image.thumbImage).appendTo(aaa);})
cList.find("li:first-child").addClass("actv");}else{$(parentModal).find("#productImg").prop('src',result.pdpMnImg);$(parentModal).find(".pdp-mn-img").attr("data-image",'');}
$(parentModal).find(".pdp-attrs .ajaxAddToCart").attr('data-skuid',result.skuId);});}}
Big.Browse.addToCart={init:function(){$(".ajaxAddToCart").live('click',function(e){e.preventDefault();var qtyRemain=$(".qtyRemain").val();var pageType=$(this).attr('data-page');var type=$(this).attr('data-type');var parentModal=$(this).parents('.modal-wrpr');var productAttr=$(parentModal).find('.pdp-attrs');var isColorSelected=$(parentModal).find('.clr-swtch').parent().hasClass('actv');var colorswathclick=$(parentModal).find(".clr-swtch").parent("li.actv");var isSizeSelected=$(parentModal).find("#productDetailSize").val();var itemQuantity=$(parentModal).find('#itemQty').val();var color=$(colorswathclick).find('a').attr('rel');var prodId=$(this).attr("data-productId");if(type!="GC")
{if(!isColorSelected){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Please Select a Color</p>").insertBefore(productAttr);return false;}else if(isSizeSelected==""){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Please Select a Size</p>").insertBefore(productAttr);return false;}}
var result=Big.Browse.ColorSizePicker.ajaxCallBack(color,isSizeSelected,prodId,'');$(parentModal).find(".qtyRemain").val(result.remainingQty);qtyRemain=$(".qtyRemain").val();if(parseInt(itemQuantity)<1||itemQuantity==""){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Quantity should not be less than or equal to 0</p>").insertBefore(productAttr);return false;}else if(isNaN(parseInt(itemQuantity))){$(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>You entered an invalid value for the Quantity Field which accepts number.</p>").insertBefore(".pdp-attrs");return false;}else if(parseInt(qtyRemain)<parseInt(itemQuantity)){$("#remainingqtyholder").text(qtyRemain+" Remain");$(".error-msg").remove();return false;}
var productData=$(this);var productId=productData.attr("data-productId");var skuId=productData.attr("data-skuid");var checkPdp=productData.attr("data-check");if(checkPdp=="true")
itemQuantity=1;$(parentModal).find(".error-msg").remove();Big.Ajax.addToCart(itemQuantity,skuId,productId,productAttr,pageType);});}}
Big.Browse.ColorSizePicker={ajaxCallBack:function(color,size,prodId,imagedisplaysequence){var jqXHR=$.ajax({url:$("#contextPath").val()+"/global/pdp/colorSizeJson.jsp",cache:false,data:{'productId':prodId,'color':color,'size':size,'imagedisplaysequence':imagedisplaysequence,},dataType:'json',async:false,success:function(data){},error:function(){}})
return $.parseJSON(jqXHR.responseText);}}
Big.Browse.ColorPicker={init:function(){$(".pdp-attrs .c-color .clr-swtch").live('click',function(e){e.preventDefault();$(".ajaxAddToCart").addClass('greyColor').val('Add To Cart').removeClass('greyColor');var parentModal=$(this).closest('.modal-wrpr');var colorswathclick=$(this);var color=$(colorswathclick).attr('rel');var prodId=$(colorswathclick).attr('data-prodid');var imagedisplaysequence=$(colorswathclick).attr('data-imagedisplaysequence');var result="";try{result=Big.Browse.ColorSizePicker.ajaxCallBack(color,'',prodId,imagedisplaysequence);$(parentModal).find(".fstorebtn").attr('data-skuid','');}finally{var options=result.items;var loadElementObj=$(parentModal).find('#productDetailSize')[0];for(i=loadElementObj.options.length;i>=0;i--){loadElementObj[i]=null;}
loadElementObj.options[loadElementObj.options.length]=new Option('Select Size','');for(i=0;i<options.length;i++){var optionName=options[i].sizeValue;var optionvalue=options[i].sizeKey;loadElementObj.options[loadElementObj.options.length]=new Option(optionName,optionvalue);}
$(parentModal).find('#getSkuId').val(result.skuId);$(parentModal).find("#skuIdHolder").text(result.skuId);$(parentModal).find(".guestAddWishlist").attr('data-skuid',result.skuId);$(parentModal).find("#skuStyleHolder").text(result.skuStyle);var priceObject=$(parentModal).find('div.priceHolder');if(result.price){var resultPrice=result.price;var priceData=resultPrice["price-data"];priceObject.html(function(){return $("<p/>").html(priceData).text();});if(resultPrice["save-price"]!=null){priceObject.append(function(){return $($("<p/>").html(resultPrice["save-price"]).text())});}
if(resultPrice["sale-end"]!=null){$(".slends").remove();priceObject.append(function(){return $($("<p/>").html(resultPrice["sale-end"]).text());});}}
$(parentModal).find("#selectedClourHolder").text(result.slectedColour);$(parentModal).find("#remainingqtyholder").text("");$(parentModal).find(".pdp-mn-thumbs ul").html("");var callToPrice=result.callForPrice;$('.cal-ord').addClass('dNone');$('.ajaxAddToCart').removeClass("dNone");if(!$('.fstorebtn').hasClass('noLinks')){$('.fstoreLink').removeClass("dNone");$('.fstorebtn').addClass('dNone');}
$('.fstorebtn').val("Find in Store");$('.ajaxAddToCart').removeClass("greyColor");$(".ajaxAddToCart").attr('disabled',false);var cList=$(parentModal).find('.pdp-mn-thumbs ul');var ImagesArray=result.Images;if(ImagesArray.length>0)
{var mainImage=ImagesArray[0].largeImage;var regularImage=ImagesArray[0].regularImage;var badgeHolder=$(parentModal).find("div.badges");var badgeUrl=result.badgeType;if(badgeUrl!=""){$(badgeHolder).html(function(){return $("<img />").attr('src',badgeUrl);});}else{if(badgeUrl=="")
$(badgeHolder).html(" ");}
$(parentModal).find("#productImg").prop('src',regularImage);$(parentModal).find(".pdp-mn-img").attr("data-image",mainImage);$.each(ImagesArray,function(index,image){var li=$('<li/>').attr('data-large-image',image.largeImage).attr('data-regular-image',image.regularImage).appendTo(cList);var aaa=$('<a/>').attr("href","#").appendTo(li);var img=$('<img/>').attr("src",image.thumbImage).appendTo(aaa);})
cList.find("li:first-child").addClass("actv");}else{$(parentModal).find("#productImg").prop('src',result.pdpMnImg);$(parentModal).find(".pdp-mn-img").attr("data-image",'');}
$(colorswathclick).parent('li').addClass('actv').siblings('li').removeClass('actv');}});}}
Big.Browse.addToWishList={init:function(){$(".ajaxAddtowishlst").live('click',function(e){e.preventDefault();var type=$(this).attr("data-type");var parentModal=$(this).parents('.modal-wrpr');var pageType=$(this).attr('data-page');var productAttr=$(parentModal).find('.pdp-attrs');var itemQuantity=$(parentModal).find('#itemQty').val();if(type=="GC"){if(parseInt(itemQuantity)<1||itemQuantity==""){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Quantity less than or equal to 0</p>").insertBefore(productAttr);return false;}}else if(pageType!="YML"){var isColorSelected=$(parentModal).find('.clr-swtch').parent().hasClass('actv');var isSizeSelected=$(parentModal).find("#productDetailSize").val();if(!isColorSelected){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Please Select a Color</p>").insertBefore(productAttr);return false;}else if(isSizeSelected==""){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Please Select a Size</p>").insertBefore(productAttr);return false;}else if(parseInt(itemQuantity)<1||itemQuantity==""){$(parentModal).find(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>Quantity less than or equal to 0</p>").insertBefore(productAttr);return false;}else if(isNaN(parseInt(itemQuantity))){$(".error-msg").remove();$('<section/>',{id:'',}).addClass('error-msg').append("<p>You entered an invalid value for the Quantity Field which accepts number.</p>").insertBefore(".pdp-attrs");return false;}}
$(parentModal).find(".error-msg").remove();$(parentModal).find('#wishlistQuantity').attr('value',itemQuantity);$(parentModal).find("#wishlistButton").trigger('click');});}}
Big.Browse.SideNavFacets={init:function(){var $checksboxes=$('aside input[type="checkbox"]');$checksboxes.bind("click",function(){var location=String(window.location.host);window.location="http://"+ location+ $(this).val();})}}
Big.Browse.FindStore={init:function(){Big.STORE.getLatLong.init(true);}}
Big.Browse.MapDirection={init:function(e){$(".goMapDirection").live('click',function(e){e.preventDefault();$("#mapDirection").submit();});}}
Big.Browse.SwatchChange={init:function(){var swatchColor=$("#product-lst .p-wrpr .colrs .clr-swtch");$(swatchColor).live('click',function(e){e.preventDefault();var thumbUrl=$(this).attr("data-thumb");var productWrapper=$(this).parents(".p-wrpr");$(productWrapper).find(".img a img").attr('src',thumbUrl);$(productWrapper).find("li a").removeClass('actv');$(this).addClass('actv');});}}
Big.Browse.SelectedMenu={init:function(){var selectMenu=$(".cam-apparel ul li a");var url=window.location.href;var urlWithoutDomain=url.replace(/^.*\/\/[^\/]+/,'');if(url.indexOf("campaignName")>=0)
{console.log(url);$('a[href="'+urlWithoutDomain+'"]').addClass('active');}else if(url.indexOf("msqax")>=0){console.log(urlWithoutDomain);$('a[href="'+urlWithoutDomain+'"]').parent('li').addClass('selectedmenu');}}}
Big.Browse.init=function(){Big.Browse.Slider.init();Big.Browse.MoreLess.init();Big.Browse.SideNavOpnClose.init();Big.Browse.ColorPicker.init();Big.Browse.addToCart.init();Big.Browse.addToWishList.init();Big.Browse.SideNavFacets.init();Big.Browse.FindStore.init();Big.Browse.MapDirection.init();Big.Browse.SizePicker.init();Big.Browse.SwatchChange.init();Big.Browse.SelectedMenu.init();}
$(document).ready(function(){Big.Browse.init();});