var Big=Big||{};Big.MegaMenu={init:function(){var $stage_menu=$('#big-menu');var $stage_menu_items=$stage_menu.children('li');if(!window.location.href.match(/store\/browse/gi)){sessionStorage.selectedOption="";$("#big-menu").find(".selectedmenu").removeClass("selectedmenu");}
$("#big-menu").find(".selectedmenu").removeClass("selectedmenu");if(sessionStorage.selectedOption==undefined||sessionStorage.selectedOption==""){var webUrl=window.location.href;this.makeCategoryHilighted(webUrl);}
else if(sessionStorage.selectedOption!=""){var webUrl=sessionStorage.selectedOption;this.makeCategoryHilighted(webUrl);}
$(".accnt-cart .minicrt").on('mouseover',function(){var len=$(".rcnt-items").find("li").length;if(len>3){$("#minicart .mcart-cntnt").css("height",500+"px").css({"width":"300px","overflow-y":"auto"});}});$stage_menu_items.on('mouseenter',function(){var $this=$(this);$this.find("a").bind({click:function(){sessionStorage.selectedOption=$(this).attr("href");}});$this.find('.cat-lnks ').find('li').find('a').bind({click:function(){sessionStorage.selectedOption=$(this).attr("href");}});$("#mega-col-right a").click(function(e){var catName=$(this).parents("#big5").closest('li').find('a').html()
$("#big-menu > li").find('a').each(function(){var selectedCat=$(this).html();if(catName==selectedCat){sessionStorage.selectedOption=$(this).attr("href");}});});if($this.find('#displayLine').val()){$('nav .big-menu div .cat-lnks').css('border-right','1px dashed #000000');}else{$('nav .big-menu div .cat-lnks').css('border-right','0px dashed #000000');}
$this.addClass('slided selected');$this.children('div').css('z-index','9999').stop(true,true).fadeIn(50,function(){$stage_menu_items.not('.slided').children('div').hide();$this.removeClass('slided');});}).bind('mouseleave',function(){var $this=$(this);$this.removeClass('selected').children('div');var url=window.location.href;var urlWithoutDomain=url.replace(/^.*\/\/[^\/]+/,'');if(url.indexOf("msqax")>=0){}});$stage_menu.on('mouseenter',function(){var $this=$(this);$this.addClass('hovered');}).live('mouseleave',function(){var $this=$(this);$this.removeClass('hovered');$stage_menu_items.children('div').hide();var url=window.location.href;var urlWithoutDomain=url.replace(/^.*\/\/[^\/]+/,'');if(url.indexOf("msqax")>=0){}})},makeCategoryHilighted:function(url){var webUrl=url;var searchURL='/store/browse/';var startIndex=webUrl.search(searchURL)+searchURL.length;var endIndex=webUrl.indexOf('/',startIndex);var resultName=webUrl.substring(startIndex,endIndex).toLowerCase();$("#big-menu > li").each(function(index,value){if(resultName=="fishing-hunting")
resultName="fishing-and-hunting";else if(resultName=="games-toys")
resultName="games-and-toys";else if(resultName=="golf-rackets")
resultName="golf-and-rackets";if($(this).find('a:eq(0)').attr("href").toLowerCase().match(resultName)){$(this).addClass("selectedmenu");}});}}
function removeBadData(){var searchData=$("#searchText").attr("value");var replacedData=searchData.replace(/\<|\>|\"|\'|\%|\;|\(|\)|\&|\+|\-/g,"");$("#searchText").attr("value",replacedData);return true;}
Big.MiniCart={init:function(){var $miniCartButton=$(".crticon, .crttxt, .minicrt .arr-dwn");$miniCartButton.on("mouseover",function(){Big.MiniCart.MiniCartOpenClose();});$(".accnt-cart .minicrt #minicartIcon").on("click",function(e){e.preventDefault();var globalCartForm=$("#addToCartForm");var contextPath=globalCartForm.find('#contextPath').val()
window.location.href=contextPath+"/cart/shoppingCart.jsp";});},MiniCartOpenClose:function(){var $miniCart=$("#minicart");var $cartSetTime=setTimeout(function(){$miniCart.slideUp('slow');},8000);$miniCart.slideDown('slow',function(){$cartSetTime;$miniCart.on('mouseover',function(){clearTimeout($cartSetTime);});$miniCart.on('mouseleave',function(){$miniCart.slideUp('slow');});});}}
Big.Ajax={addToCart:function(quantity,skuId,productId,object,pageType){var globalCartForm=$("#addToCartForm");$(".field-invalid-txt").remove();globalCartForm.find('.itemQuantity').val(quantity);globalCartForm.find('.itemSku').val(skuId);globalCartForm.find('.itemProductId').val(productId);$.ajax({url:globalCartForm.attr('action'),data:globalCartForm.serialize(),type:'POST',dataType:'json',success:function(data){if(data.success){var miniCartUrl=globalCartForm.find('#contextPath').val();if(pageType=="modal"){var $object=$(object).parents("section."+productId);Big.Modals.CloseModal($object)}
Big.Ajax.updateMiniCart(miniCartUrl+"/common/includes/miniCartLineItems.jsp");}
else{$(".error-msg").remove();$('<section/>',{id:''}).addClass('error-msg').append("<p>"+data.message+"</p>").insertBefore(object);}},error:function(){}});},updateMiniCart:function(url){$.ajax({url:url,cache:false,data:'',dataType:'html',success:function(data){$('.minicrt').replaceWith(data);},error:function(){},complete:function(){var cartItemQty=$("#minicartIcon .crticon").text();var itemQtyLength=cartItemQty.length;if(itemQtyLength>3){$("header .minicrt .crticon").css({"background":"url('/static/big5/images/buttons-icons/cart-icon.png') no-repeat scroll 24px 2px rgba(0, 0, 0, 0)","width":"47px"});}else if(itemQtyLength>2){$("header .minicrt .crticon").css({"background":"url('/static/big5/images/buttons-icons/cart-icon.png') no-repeat scroll 14px 2px rgba(0, 0, 0, 0)","width":"37px"});}else if(itemQtyLength>1){$("header .minicrt .crticon").css({"background":"url('/static/big5/images/buttons-icons/cart-icon.png') no-repeat scroll 4px 0 rgba(0, 0, 0, 0)"});}
Big.MiniCart.MiniCartOpenClose();Big.MiniCart.init();var len=$(".rcnt-items").find("li").length;if(len>3){$("#minicart .mcart-cntnt").css("height",500+"px").css({"width":"300px","overflow-y":"auto"});}}});},quickLookAjax:function($productId,$skudId,$object,$prodName,$brandName,$displaySequence){var contextPath=$('#contextPath').val();$.ajax({url:contextPath+'/global/pdp/quickOverview.jsp',data:{'productId':$productId,'skuId':$skudId,'prodName':$prodName,'brandName':$brandName,'imagedisplaysequence':$displaySequence},type:'POST',dataType:'html',async:false,success:function(data){$object.html(data);$(".fb").attr("addthis:url","http%3A%2F%2F"+window.location.host+""+contextPath+"/details/"+$.trim($brandName).split(" ").join("-")+"-"+$.trim($prodName).split(" ").join("-")+"/"+$productId+"/_/A-"+$skudId);$(".fb").attr("addthis:title",$brandName+" "+$prodName);$(".pntrst").attr("addthis:url",window.location.host+"/store/details/"+$.trim($brandName).split(" ").join("-")+"-"+$.trim($prodName).split(" ").join("-")+"/"+$productId+"/_/A-"+$skudId);$(".twtr").attr("addthis:url",window.location.host+""+contextPath+"/details/"+$.trim($brandName).split(" ").join("-")+"-"+$.trim($prodName).split(" ").join("-")+"/"+$productId+"/_/A-"+$skudId);$(".twtr").attr("addthis:title",$brandName+" "+$prodName);$(".mail").attr("addthis:url",window.location.host+"/store/details/"+$.trim($brandName).split(" ").join("-")+"-"+$.trim($prodName).split(" ").join("-")+"/"+$productId+"/_/A-"+$skudId);$(".mail").attr("addthis:title",$brandName+" "+$prodName);},error:function(){}})},findInStoreAjax:function($productId,$skudId,$object,$styleId,$selectedSize,colorActive,$displaySequence){var contextPath=$('#contextPath').val();var color=$(colorActive).find('a').attr('rel');var selectedColor="";$.ajax({url:contextPath+'/global/pdp/findInStore.jsp',data:{'productId':$productId,'skuId':$skudId,'styleId':$styleId,'colorActive':color,'selectedColor':color,'selectedSize':$selectedSize,'imagedisplaysequence':$displaySequence},method:'post',dataType:'html',async:false,success:function(data){var $thisObject=$('.modal-wrapper').parents("section."+$productId);Big.Modals.CloseModal($thisObject)
$object.html(data);var zipcode="zipcode=";var rangeMiles="rangeMiles=";var cookieDetails=document.cookie.split(';');var cookieZipcode="";var cookieRangeMiles="";for(var i=0;i<cookieDetails.length;i++)
{var cookieValues=cookieDetails[i].trim();if((cookieValues.substring(0,cookieValues.length)).indexOf(zipcode)>=0){cookieZipcode=cookieValues.substring(zipcode.length,cookieValues.length);}else if((cookieValues.substring(0,cookieValues.length)).indexOf(rangeMiles)>=0){cookieRangeMiles=cookieValues.substring(rangeMiles.length,cookieValues.length);}}
if(cookieZipcode!=""&&cookieRangeMiles!="")
{$("#storeLocatorAddressField").val(cookieZipcode);$("#miles").val(cookieRangeMiles);}},error:function(){}})}}
Big.SocialScript={init:function(){window.addthis_config={"data_track_addressbar":true};window.addthis_config.pubid='ra-514ba5153b6b335f';var script='http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-514ba5153b6b335f';if(window.addthis){window.addthis=null;window._adr=null;window._atc=null;window._atd=null;window._ate=null;window._atr=null;window._atw=null;}
$.getScript(script);}}
Big.Modals={init:function(){var $ModalButton=$("[data-modal-class]");var $CloseButton=$(".modal .close, .modal .linkCancel ");$ModalButton.live("click",function(e){e.preventDefault();var $name=$(this).attr("data-modal-class");var $key=$(this).attr("data-nickName");var $name=$name.split('.');var $name=$name[2];Big.Modals.OpenModal($name,$key,$(this));});$CloseButton.live("click",function(e){e.preventDefault();var myVideo=document.getElementById("videoStop");if(myVideo!=null&myVideo!=undefined){if(navigator.appVersion.indexOf("MSIE 8.")==-1){myVideo.pause();}}
$object=$(this).closest("section.modal");Big.Modals.CloseModal($object);});},OpenModal:function($name,$key,$object){var $Modal=$('.modal');if($($Modal).hasClass($name)){if($name=="deleteAddress"){var $textAddress=$object.parent('address').html();$Modal.find("address").html($textAddress);$Modal.find('.editLink').remove();$Modal.find('.deleteLink').remove();$("input[name='nickname']").val($key);}
if($name=="QuickVw"){$newClass=$object.attr('data-productId');$skuId=$object.attr('data-skuId');$prodName=$object.attr('data-productName');$brandName=$object.attr('data-brandName');$displaySequence=$object.attr('data-imagedisplaysequence');$imageName=$object.attr('data-image');var dataPageType=$object.attr('data-page-type');if(dataPageType=='YML'){var pdpOgMetas=$('meta[name=imageOg]').attr("content");$("#pdpOgMeta").val(pdpOgMetas);}
$('meta[name=imageOg]').attr("content",$imageName);if($($Modal).hasClass($newClass))
$name=$newClass;else{$('<section/>',{id:$newClass}).addClass('modal QuickVw '+$newClass).insertAfter('section#wrapper');$quickLookContainer=$("section#"+$newClass);Big.Ajax.quickLookAjax($newClass,$skuId,$quickLookContainer,$prodName,$brandName,$displaySequence);Big.SocialScript.init();$name=$newClass;}}if($name=="ordr-procss"){$("#submitOrderBtn").trigger('click');}
if($name=="FindInStore"){$newClass=$object.attr('data-productid');$newClass=$newClass+'1';$skuId=$object.attr('data-skuid');$styleId=$object.attr('data-style');$productId=$object.attr("data-productid");$displaySequence=$object.attr('data-imagedisplaysequence');$dataStoreQl=$object.attr("data-store");$selectedSize=$object.closest(".pdp-desc-attrs").find("#productDetailSize").val();$quickLookContainer=$("section#"+$newClass);var colorActive="";var quickViewHid=$(".quickViewHid").val();if($dataStoreQl!=null&&$dataStoreQl!=undefined&&$dataStoreQl=='sQl'){colorActive=$object.closest('.quickOverviewDesc').find(".clr-swtch").parent("li.actv");}else{colorActive=$(".clr-swtch").parent("li.actv");}
if($($Modal).hasClass($newClass)){$name=$newClass;Big.Ajax.findInStoreAjax($productId,$skuId,$quickLookContainer,$styleId,$selectedSize,colorActive,$displaySequence);}
else{$('<section/>',{id:$newClass}).addClass('modal FindInStore '+$newClass).insertAfter('section#wrapper');$quickLookContainer=$("section#"+$newClass);Big.Ajax.findInStoreAjax($productId,$skuId,$quickLookContainer,$styleId,$selectedSize,colorActive,$displaySequence);$name=$newClass;}}
if($name=="watchvideo"){$videoUrl=$object.attr('href');var $thisObject=$('.modal-wrapper').parents("section.QuickVw");$('#videoSrc').attr("src",$videoUrl);$(".watchvideo video")[0].load();Big.Modals.CloseModal($thisObject)}
Big.UpdateImages.init();$("."+$name).show();window.setTimeout(function(){$("."+$name).find(".modal-wrapper").addClass('modal-wrapper-visible');},300);}else{alert('The Modal Window is not there Please get that');}},CloseModal:function($object){var pdpOgMeta=$("#pdpOgMeta").val();if(pdpOgMeta!=""&&pdpOgMeta!=undefined){$('meta[name=imageOg]').attr("content",pdpOgMeta);}
$object.fadeOut().end().find(".modal-wrapper").removeClass('modal-wrapper-visible');}}
Big.BrandSlide={init:function(){var isOPen=false;var $Button=$(".browsebrand span, .browsebrand a");var $BrandContent=$(".brands-byname");var $HideBrandContent=$(".browsebrand");var $brand_wrpr=$("#brand_wrpr a");$brand_wrpr.show();var $letter=$("#bb_menu_header a");Big.BrandSlide.BrandDisplaybyLetter($letter);$HideBrandContent.bind("click",function(e){e.preventDefault();if(!isOPen){$Button.parent('li').addClass("opnd");$BrandContent.show();isOPen=true;}else{if($(e.target).parents('.browsebrand').size()>0){$Button.parent('li').removeClass("opnd");$BrandContent.hide();isOPen=false;}}});},BrandDisplaybyLetter:function($letter){$($letter).live("click",function(){$("#bb_menu_header a").removeClass('actv');$(this).addClass('actv');$ltr=$(this).text();var regex;if($ltr!="#")
regex=new RegExp("^"+$ltr,"i");else if($ltr=="#")
regex=new RegExp("^[0-9].*","i");var flag=0;if($ltr!=="Featured Brand"){$("#brand_wrpr span.no-bran").remove();$('#brand_wrpr a').hide().filter(function(){if($(this).text().charAt(0).match(regex)){$(this).show();flag=1;}})
if(flag==0)
$("#brand_wrpr").append("<span class='no-bran'>No Brands Available</span>");}else if($ltr=="Featured Brand"){$('#brand_wrpr a[alt=featured]').show();}})}}
Big.openModalAfterRefresh={init:function(){var url=window.location.href;var request={};var pairs=url.substring(url.indexOf('?')+ 1).split('&');for(var i=0;i<pairs.length;i++){var pair=pairs[i].split('=');request[decodeURIComponent(pair[0])]=decodeURIComponent(pair[1]);}
if(request.popup!=undefined){Big.Modals.OpenModal(request.popup);}}}
Big.FetchCityFromZip={init:function(){$("#big5Zip").live('keyup',function(){if($(this).val().length==5){var zip=$(this).val();var geocoder=new google.maps.Geocoder();geocoder.geocode({'address':$("#big5Zip").val()+'|components:country:US'},function(result,status){var state="N/A";var city="N/A";for(var component in result[0]['address_components']){for(var i in result[0]['address_components'][component]['types']){console.log(result[0]['address_components']);if(result[0]['address_components'][component]['types'][i]=="administrative_area_level_1"){state=result[0]['address_components'][component]['short_name'];city=result[0]['address_components'][1]['long_name'];$("#big5City").attr('value',city);$("#big5State option[value="+state+"]").attr('selected',true);}}}});}});}}
Big.Pagination={init:function($itemsCount,$perPageItems,$preNextButton){var $totalPages=Math.ceil($itemsCount/$perPageItems);Big.Pagination._showHideButtons($(".prevButton"),false);if($totalPages==1){Big.Pagination._showHideButtons($(".prevButton"),false);Big.Pagination._showHideButtons($(".nxtButton"),false);}
Big.Pagination._updatePageNumbers(1,$totalPages);$('div[data-paginate=paginationContainer]').hide().filter(function(){$("div[data-paginate=paginationContainer]").each(function(){var $recordNumber=$(this).attr('data-paginate-record');if($recordNumber>=0&&$recordNumber<=parseInt($perPageItems))
$(this).show();})})
if($preNextButton){$("<input />",{id:'currentPage',type:'hidden'}).attr('value',1).appendTo("#pagesContainer");}else{}
$(".prevButton").click(function(){var $currentPage=parseInt($("#currentPage").val());Big.Pagination._prevButtonClick($currentPage,$perPageItems,$totalPages,this);});$(".nxtButton").click(function(){var $currentPage=parseInt($("#currentPage").val());Big.Pagination._nextButtonClick($currentPage,$perPageItems,$totalPages,this);});},_prevButtonClick:function(pCurrentPage,perPageItems,totalPages,object){Big.Pagination._showHideButtons($(".nxtButton"),true);$('div[data-paginate=paginationContainer]').hide().filter(function(){$("div[data-paginate=paginationContainer]").each(function(){var getCurrentPage=pCurrentPage;var $recordNumber=$(this).attr('data-paginate-record');if($recordNumber<=((getCurrentPage-1)*perPageItems)&&$recordNumber>(getCurrentPage-2)*perPageItems){$(this).show();}})})
$("#currentPage").attr('value',pCurrentPage-1);Big.Pagination._updatePageNumbers(pCurrentPage-1,totalPages);if(pCurrentPage-1==1)
Big.Pagination._showHideButtons(object,false);else
Big.Pagination._showHideButtons(object,true);},_nextButtonClick:function(nCurrentPage,perPageItems,totalPages,object){Big.Pagination._showHideButtons($(".prevButton"),true);$('div[data-paginate=paginationContainer]').hide().filter(function(){$("div[data-paginate=paginationContainer]").each(function(){var getCurrentPage=nCurrentPage;var $recordNumber=$(this).attr('data-paginate-record');if($recordNumber>(getCurrentPage*perPageItems)&&$recordNumber<=(getCurrentPage+1)*perPageItems){$(this).show();}})})
$("#currentPage").attr('value',nCurrentPage+1);Big.Pagination._updatePageNumbers(nCurrentPage+1,totalPages);if(nCurrentPage+1==totalPages)
Big.Pagination._showHideButtons(object,false);else
Big.Pagination._showHideButtons(object,true);},_updatePageNumbers:function(currentPage,totalPages){$(".pageNumbers").text(currentPage+" / "+ totalPages);},_showHideButtons:function(buttonObject,checkShow){if(checkShow)
$(buttonObject).show();else
$(buttonObject).hide();}}
Big.RemoveItem={init:function(){$(".removItemFromCart").live('click',function(e){e.preventDefault();var commerceItem=$(this).attr("data-item-id");var getRemoveForm=$("form#removeCartForm");getRemoveForm.find("#commerceId").attr('value',commerceItem);getRemoveForm.find("#removeButton").trigger("click");})}}
Big.UpdateQuantity={init:function(){$(".updateCart").click(function(e){e.preventDefault();var productId=$(this).attr("data-item-id");var skuId=$(this).attr("data-catalogRef-id");var availableQty=$("#availQuantity_"+productId).val();var getUpdateItemForm=$("form#updateCartForm");var quantity=$("#qty_"+productId).val();if(parseInt(quantity)>parseInt(availableQty)){$("#qty_"+productId).addClass("error");$('<section/>',{id:''}).addClass('field-invalid-txt').append("<span />").append("<p>Sorry, but we only have "+availableQty+" of these available. Change the quantity to "+availableQty+" or less. Thanks!</p>").insertAfter("#qty_"+productId);return false;}
$("#qty_"+productId).removeClass("error");$(".oldCartItemQuantity").each(function(){$(this).appendTo(getUpdateItemForm);});getUpdateItemForm.find(".updateProductId").attr('value',productId);getUpdateItemForm.find(".productIds").attr('value',productId);getUpdateItemForm.find(".skuId").attr('value',skuId);getUpdateItemForm.find("input#oldQty_"+productId).attr('value',quantity);getUpdateItemForm.find("#updateButton").trigger("click");})}}
Big.MoveToWishList={init:function(){$(".moveToWishList").click(function(e){e.preventDefault();var itemId=$(this).attr("data-item-id");var commerceItem=$(this).attr("data-catalogRef-id");var wishlist=$(this).attr("data-wishlist-id");var productId=$(this).attr("data-product-id");var productname=$(this).attr("data-product-name");var brandName=$(this).attr("data-brand-name");var getWishlistForm=$("form#moveWishListForm");var url=getWishlistForm.find(".successUrl").val();var quantity=$("#oldQty_"+itemId).val();getWishlistForm.find(".productId").attr('value',productId);getWishlistForm.find(".wishlst").attr('value',wishlist);getWishlistForm.find(".successUrl").attr('value',url+productname+"&brandName="+brandName);getWishlistForm.find(".selectedCatalogRef").attr('value',commerceItem);getWishlistForm.find(".skuIdHolderWish").attr('value',commerceItem);getWishlistForm.find(".brandName").attr('value',brandName);getWishlistForm.find(".selectedQnt").attr('value',quantity);getWishlistForm.find(".wishlistButton").trigger("click");})}}
Big.GuestMoveToWishlist={init:function(){$(".guestAddWishlist").live('click',function(e){e.preventDefault();var type=$(this).attr("data-type");var skudId=$(this).attr("data-skuid");var productId=$(this).attr("data-product-id");var productname=$(this).attr("data-product-name");var brandName=$(this).attr("data-brand-name");var parentModal=$(this).parents('.pdp-desc-attrs');var itemQuantity=$(parentModal).find('#itemQty').val();var isSizeSelected=$(parentModal).find("#productDetailSize").val();if(type=="GC"){if(parseInt(itemQuantity)<1||itemQuantity==""){$(".field-invalid-txt").remove();$('<section/>',{id:''}).addClass('field-invalid-txt').append("<span />").append("<p>Quantity should not be less than or equal to 0</p>").insertBefore(".pdp-attrs");return false;}else if(isSizeSelected==""){$(".error-msg").remove();$('<section/>',{id:''}).addClass('error-msg').append("<p>Please Select Amount</p>").insertBefore(".pdp-attrs");return false;}}else if(type!="cart"){var isColorSelected=$(parentModal).find('.clr-swtch').parent().hasClass('actv');var isSizeSelected=$(parentModal).find("#productDetailSize").val();if(!isColorSelected){$(".error-msg").remove();$('<section/>',{id:''}).addClass('error-msg').append("<p>Please Select a Color</p>").insertBefore(".pdp-attrs");return false;}else if(isSizeSelected==""){$(".error-msg").remove();$('<section/>',{id:''}).addClass('error-msg').append("<p>Please Select a Size</p>").insertBefore(".pdp-attrs");return false;}else if(parseInt(itemQuantity)<1||itemQuantity==""){$(".error-msg").remove();$('<section/>',{id:''}).addClass('error-msg').append("<p>Quantity should not be less than or equal to 0</p>").insertBefore(".pdp-attrs");return false;}}
var getWishlistForm=$("form#guestWishlist");getWishlistForm.find(".productId").attr('value',productId);getWishlistForm.find(".skuId").attr('value',skudId);getWishlistForm.find(".addedToWishList").attr('value',"true");getWishlistForm.find(".quantity").attr('value',itemQuantity);getWishlistForm.find(".productName").attr('value',productname);getWishlistForm.find(".brandName").attr('value',brandName);if(type=="pdp"||type=="GC"){getWishlistForm.find("#frmCart").attr('value',"false");}
else if(type=="cart"){getWishlistForm.find("#frmCart").attr('value',"true");getWishlistForm.find(".quantity").attr('value',$(this).attr("data-quantity"));}
getWishlistForm.submit();})}}
Big.AutoSearchResult={init:function(){$("#searchText").endecaSearchSuggest({searchTextId:"searchText",minAutoSuggestInputLength:3,autoSuggestServiceUrl:'/store/global/autosuggestjson.jsp',collection:"",containerClass:"dimSearchSuggContainer",defaultImage:'no_image.gif'});}}
Big.ShowHideDivbyRadio={init:function(){var radcheck=$(".shuffle-div");var radcheckd=$(".shuffle-div:checked");var checkboxChkd=$('input[type="checkbox"]:checked').attr('id');$("body").find("."+$(radcheckd).attr('id')).slideDown("slow");$("body").find(".shuffle."+checkboxChkd).hide();var guestEmail=$("input[name='guest_email']").val();if(guestEmail!=""&&guestEmail!=undefined){$("#shippingForm #gst-form").attr('checked','checked');$("body").find("#guestEmailForm").slideDown("slow");}
radcheck.bind("click",function(){$("body").find(".shuffle").hide();$("body").find("."+$(this).attr('id')).slideDown("slow");if($(this).prop('checked')==true){$("body").find(".shuffle."+checkboxChkd).hide();}})}}
Big.ImgZooming={init:function(){$zoomImg=$('.cloud-zoom img').attr('data-zoom-image');if($zoomImg!=undefined){$('#productImg').elevateZoom({cursor:'crosshair',zoomWindowFadeIn:500,zoomWindowFadeOut:750,zoomWindowWidth:356,zoomWindowHeight:356,gallery:'pdpmngallry',galleryActiveClass:'active',imageCrossfade:true})}}}
Big.UpdateImages={init:function(){$(".pdp-mn-thumbs ul li:first-child").addClass("actv");$(".pdp-mn-thumbs ul li").live('click',function(e){e.preventDefault();var largeImageUrl=$(this).find(".zoom-thumb").attr("data-zoom-image");var regularImageUrl=$(this).attr("data-regular-image");var imageContainer=$(this).parents(".pdp-imgs-cntnr");$(imageContainer).find(".pdp-mn-img").attr("data-image",largeImageUrl);$(imageContainer).find("#productImg").attr("src",regularImageUrl);$(imageContainer).find("#productImg").attr("data-zoom-image",largeImageUrl);$(imageContainer).find("#productImg").data("zoom-image",largeImageUrl);var imageContainerMain=$(".cloud-zoom");var zoomImageObj=$(imageContainerMain).find(".zoomWrapper");$(imageContainerMain).attr("data-image",largeImageUrl);$(zoomImageObj).find("img").attr("data-zoom-image",largeImageUrl);$(zoomImageObj).find("img").attr("data-zoom-image",largeImageUrl);$(zoomImageObj).find("img").data("zoom-image",largeImageUrl);Big.ImgZooming.init();$(this).addClass("actv");$(this).siblings().removeClass("actv");})}}
Big.Search={init:function(e){$("#searchButton").live('click',function(e){e.preventDefault();var searchText=$("#searchText").val();if(searchText!=null&&searchText!="Search by Keywords or Product SKU"){$("#searchform").submit();}else{$("#searchText").css("color","red");}});$("#searchText").focus(function(){$("#searchText").removeAttr("style");})}}
Big.SetOptIn={init:function(e){$("#optInEmail").live("click",function(){$('#flagId').val(this.value);});}}
Big.showMobileSMS={init:function(e){$('#ETeamMobileSms').live("click",function(){if($(this).is(':checked'))
{$(".notDisplayMobileNoDev1").show();}else{$(".notDisplayMobileNoDev1").hide();}});$("#eteamSignUp").submit(function(){var checked=$("#eteamSignUp input:checked").length>0;if(!checked){$(".error-msg").remove();$('<section/>',{id:''}).addClass('error-msg').append("<p>Please select at least one publication</p>").insertBefore(".e-team-form");return false;}});}}
Big.SignIn={init:function(){var $hideShowLoginOnMouse=$(".accnt-cart .sign");var $hideShowLoginClass=$(".account-links");$hideShowLoginOnMouse.bind({mouseleave:function(){$hideShowLoginClass.hide();}});$hideShowLoginOnMouse.bind({mouseover:function(){$hideShowLoginClass.show();}});}}
Big.FontCheck={doesFontExist:function(fontName){var canvas=document.createElement("canvas");var context=canvas.getContext("2d");var text="abcdefghijklmnopqrstuvwxyz0123456789";context.font="72px monospace";var baselineSize=context.measureText(text).width;context.font="72px '"+ fontName+"', monospace";var newSize=context.measureText(text).width;delete canvas;if(newSize==baselineSize){return false;}else{return true;}},isCanvasSupported:function(){var elem=document.createElement('canvas');return!!(elem.getContext&&elem.getContext('2d'));}}
Big.init=function(){Big.MegaMenu.init();Big.MiniCart.init();Big.Modals.init();Big.BrandSlide.init();Big.openModalAfterRefresh.init();Big.RemoveItem.init();Big.MoveToWishList.init();Big.UpdateQuantity.init();Big.AutoSearchResult.init();Big.ShowHideDivbyRadio.init();Big.UpdateImages.init();Big.GuestMoveToWishlist.init();Big.Search.init();Big.SetOptIn.init();Big.showMobileSMS.init();Big.SignIn.init();if(Big.FontCheck.isCanvasSupported()){var isFontExists=Big.FontCheck.doesFontExist("geneva");if(isFontExists==true){$(".cart-lft-cntnt").css("font-size","11px");$(".cart-rght-cntnt").css("font-size","11px");$(".notsignedin").css("width","206px");$(".pagination .sort-slct").css("width","188px");}else{$(".cart-lft-cntnt").css("font-size","11px");$(".cart-rght-cntnt").css("font-size","11px");$(".notsignedin").css("width","188px");}}else{$(".cart-lft-cntnt").css("font-size","11px");$(".cart-rght-cntnt").css("font-size","11px");$(".notsignedin").css("width","206px");}
if(navigator.userAgent.match(/Chrome/gi)){$("#promosName").prepend("<br>");}
var pagLength=$("#right-content .pagination .paginates ul li").find("*").length;if(pagLength==2){var pagValue=$.trim($("#right-content .pagination .paginates ul li").find("a").html());if(pagValue==1){$("#right-content .pagination .paginates ul li").css("margin-right","8px");}}
$(".ttip.check-forgot").focus(function(){$(this).css("border","1px dotted #000");}).blur(function(){$(this).css("border","");});var cartItemQty=$("#minicartIcon .crticon").text();var itemQtyLength=cartItemQty.length;if(itemQtyLength>3){$("header .minicrt .crticon").css({"background":"url('/static/big5/images/buttons-icons/cart-icon.png') no-repeat scroll 24px 2px rgba(0, 0, 0, 0)","width":"47px"});}else if(itemQtyLength>2){$("header .minicrt .crticon").css({"background":"url('/static/big5/images/buttons-icons/cart-icon.png') no-repeat scroll 14px 2px rgba(0, 0, 0, 0)","width":"37px"});}else if(itemQtyLength>1){$("header .minicrt .crticon").css({"background":"url('/static/big5/images/buttons-icons/cart-icon.png') no-repeat scroll 4px 0 rgba(0, 0, 0, 0)"});}}
$(document).ready(function(){timerCounter=0;stopFlag=false;typing=false;if($(".headerSuccessURL").length>0)
if(document.referrer==null){var contextPath=$('#contextPath').val();$(".headerSuccessURL").val(contextPath+"/account/dashboard.jsp");}else{$(".headerSuccessURL").val(document.referrer);}
Big.init();})