
var Big=Big||{};Big.STORE=Big.STORE||{};Big.STORE={StatePicker:function(){$(".mapclass").on('click',function(){$('#storeState').val($(this).attr('rel'));$('#zipForm').submit();})}}
Big.STORE.ColorSizePicker={ajaxCallBack:function(color,size,prodId){var contextPath=$('#contextPath').val();var jqXHR=$.ajax({url:contextPath+"/global/pdp/colorSizeJson.jsp",cache:false,data:{'productId':prodId,'color':color,'size':size,},dataType:'json',async:false,success:function(data){},error:function(){}})
return $.parseJSON(jqXHR.responseText);}}
Big.STORE.Cookies={init:function($pdpPage){$("#modalFindStore #productDetailSize").live('change',function(e){e.preventDefault();var contextPath=$('#contextPath').val();var zipcode="zipcode=";var rangeMiles="rangeMiles=";var cookieDetails=document.cookie.split(';');var cookieZipcode="";var cookieRangeMiles="";for(var i=0;i<cookieDetails.length;i++)
{var cookieValues=cookieDetails[i].trim();if((cookieValues.substring(0,cookieValues.length)).indexOf(zipcode)>=0){cookieZipcode=cookieValues.substring(zipcode.length,cookieValues.length);}else if((cookieValues.substring(0,cookieValues.length)).indexOf(rangeMiles)>=0){cookieRangeMiles=cookieValues.substring(rangeMiles.length,cookieValues.length);}}
if(cookieZipcode!=""&&cookieRangeMiles!="")
{var parentModal=$(this).closest('.modal-wrpr');var colorswathclick=$(parentModal).find(".clr-swtch").parent("li.actv");var color=$(colorswathclick).find('a').attr('rel');var prodId=$(colorswathclick).find('a').attr('data-prodid');var size=$(this).val();var result=Big.STORE.ColorSizePicker.ajaxCallBack(color,size,prodId);var skuId=result.skuId;var geocoder=new google.maps.Geocoder();geocoder.geocode({'address':cookieZipcode},function(results,status){if(status==google.maps.GeocoderStatus.OK){address=results[0].geometry.location;var lat=results[0].geometry.location.lat();var lng=results[0].geometry.location.lng();if($pdpPage){if(skuId==''||skuId==null){$('.pdp-attrs .sizeError').text("Please select the size");}else{$.ajax({url:contextPath+'/integration/includes/findInStoreDetails.jsp',data:{'skuId':skuId,'lat':lat,'lng':lng,'miles':cookieRangeMiles},method:'post',dataType:'html',async:false,success:function(data){$('.inventry-dtls-wrpr').html(data);$("#storeLocatorAddressField").val(cookieZipcode);$("#miles").val(cookieRangeMiles);},error:function(){}})}}}else if(status==google.maps.GeocoderStatus.ZERO_RESULTS){$('.errorNoResults').text("Please enter valid address");}});}});}}
if(typeof String.prototype.trim!=='function'){String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,'');}}
Big.STORE.getLatLong={init:function($pdpPage){var zipcode="zipcode=";var rangeMiles="rangeMiles=";var cookieDetails=document.cookie.split(';');var cookieZipcode="";var cookieRangeMiles="";for(var i=0;i<cookieDetails.length;i++)
{var cookieValues=cookieDetails[i].trim();(function(str){if(typeof(str.prototype.trim)==='undefined'){str.prototype.trim=function(){return $.trim(this);};}})(String);if((cookieValues.substring(0,cookieValues.length)).indexOf(zipcode)>=0){cookieZipcode=cookieValues.substring(zipcode.length,cookieValues.length);}else if((cookieValues.substring(0,cookieValues.length)).indexOf(rangeMiles)>=0){cookieRangeMiles=cookieValues.substring(rangeMiles.length,cookieValues.length);}}
if(cookieZipcode!=""&&cookieRangeMiles!="")
{$("#storeLocatorAddressField").val(cookieZipcode);$("#miles").val(cookieRangeMiles);}
$("#storeLocatorAddressField").live('focus',function(e){$('.errorNoResults').text("");});$("#store_find_button").live('click',function(e){e.preventDefault();if(!$("#find-store").validationEngine('validate')){return false;}
if(!$("#store-search").validationEngine('validate')){return false;}
var contextPath=$('#contextPath').val();var address=$('#storeLocatorAddressField').val();var e=document.getElementById("miles");var strOption=e.options[e.selectedIndex].value;document.cookie="zipcode="+address+";path=/";document.cookie="rangeMiles="+strOption+";path=/";var geocoder=new google.maps.Geocoder();geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){address=results[0].geometry.location;var lat=results[0].geometry.location.lat();var lng=results[0].geometry.location.lng();if($pdpPage){var skuId=$("#getSkuId").val();if(skuId==''||skuId==null){$('.pdp-attrs .sizeError').text("Please select a size");}else{$.ajax({url:contextPath+'/integration/includes/findInStoreDetails.jsp',data:{'skuId':skuId,'lat':lat,'lng':lng,'miles':strOption},method:'post',dataType:'html',async:false,success:function(data){$('.inventry-dtls-wrpr').html(data);},error:function(){}})}}else{$("#latid").val(lat);$("#lngid").val(lng);$("form.findForm").submit();}}else if(status==google.maps.GeocoderStatus.ZERO_RESULTS){$('.errorNoResults').text("Please enter valid address");}});})}}
Big.STORE.loadMap={init:function(){var url=window.location.href;var request={};var pairs=url.substring(url.indexOf('?')+ 1).split('&');for(var i=0;i<pairs.length;i++){var pair=pairs[i].split('=');request[decodeURIComponent(pair[0])]=decodeURIComponent(pair[1]);}
if(request.showmap=='yes'){var lat1=new Array();$("input[name=latHidden]").each(function(){lat1.push($(this).val());});var lng1=new Array();$("input[name=lngHidden]").each(function(){lng1.push($(this).val());});var storeName1=new Array();$("input[name=nameHidden]").each(function(){storeName1.push($(this).val());});var address1=new Array();$("input[name=addressHidden]").each(function(){address1.push($(this).val());});var phonenumber1=new Array();$("input[name=phonenumberHidden]").each(function(){phonenumber1.push($(this).val());});var regularHoursMonToThu=new Array();$("input[name=regularHoursMonToThu]").each(function(){regularHoursMonToThu.push($(this).val());});var regularHoursFriday=new Array();$("input[name=regularHoursFriday]").each(function(){regularHoursFriday.push($(this).val());});var regularHoursSaturday=new Array();$("input[name=regularHoursSaturday]").each(function(){regularHoursSaturday.push($(this).val());});var regularHoursSunday=new Array();$("input[name=regularHoursSunday]").each(function(){regularHoursSunday.push($(this).val());});var holidayHoursMonToThu=new Array();$("input[name=holidayHoursMonToThu]").each(function(){holidayHoursMonToThu.push($(this).val());});var holidayHoursFriday=new Array();$("input[name=holidayHoursFriday]").each(function(){holidayHoursFriday.push($(this).val());});var holidayHoursSaturday=new Array();$("input[name=holidayHoursSaturday]").each(function(){holidayHoursSaturday.push($(this).val());});var holidayHoursSunday=new Array();$("input[name=holidayHoursSunday]").each(function(){holidayHoursSunday.push($(this).val());});var id=new Array();$("input[name=idHidden]").each(function(){id.push($(this).val());});var map=new google.maps.Map(document.getElementById('map'),{zoom:5,center:new google.maps.LatLng(request.lat==null?lat1[0]:request.lat,request.lng==null?lng1[0]:request.lng),mapTypeId:google.maps.MapTypeId.ROADMAP});var infowindow=new google.maps.InfoWindow();var big5Icon;big5Icon=$("#customMarker").val();var linkHidden=$("#linkHidden").val();var directStore=$("#directStore").val();for(var z=0;z<lat1.length;z++){var marker=new google.maps.Marker({position:new google.maps.LatLng(lat1[z],lng1[z]),map:map,icon:big5Icon,});google.maps.event.addListener(marker,'click',(function(marker,z){var popUpDisplay="<div class='str-popup'><h2>";popUpDisplay+=storeName1[z]+"<h2><p>";popUpDisplay+=address1[z]+"</p><p class='pop_phone'><span>Phone:</span>";popUpDisplay+=phonenumber1[z]+"</p><div class='one'>";if(regularHoursMonToThu[z]!=""||regularHoursFriday[z]!=""||regularHoursSaturday[z]!=""||regularHoursSunday[z]!=""){popUpDisplay+="<p class='red'><span>Regular Hours:</span></p>";}
if(regularHoursMonToThu[z]!=""&&regularHoursMonToThu[z]!=undefined){popUpDisplay+="<p>Mon-Thurs:"+regularHoursMonToThu[z]+"</p>";}
if(regularHoursFriday[z]!=""&&regularHoursFriday[z]!=undefined){popUpDisplay+="<p>Fri:"+regularHoursFriday[z]+"</p>";}
if(regularHoursSaturday[z]!=""&&regularHoursSaturday[z]!=undefined){popUpDisplay+="<p>Sat:"+regularHoursSaturday[z]+"</p>";}
if(regularHoursSunday[z]!=""&&regularHoursSunday[z]!=undefined){popUpDisplay+="<p>Sun:"+regularHoursSunday[z]+"</p>";}
popUpDisplay+="</div><div class='two'>";if(holidayHoursMonToThu[z]!=""||holidayHoursFriday[z]!=""||holidayHoursSaturday[z]!=""||holidayHoursSunday[z]!=""){popUpDisplay+="<p class='red'><span>Holiday Hours:</span></p>";}
if(holidayHoursMonToThu[z]!=""&&holidayHoursMonToThu[z]!=undefined){popUpDisplay+="<p class='red'>Mon-Thurs:"+holidayHoursMonToThu[z]+"</p>";}
if(holidayHoursFriday[z]!=""&&holidayHoursFriday[z]!=undefined){popUpDisplay+="<p class='red'>Fri:"+holidayHoursFriday[z]+"</p>";}
if(holidayHoursSaturday[z]!=""&&holidayHoursSaturday[z]!=undefined){popUpDisplay+="<p class='red'>Sat:"+holidayHoursSaturday[z]+"</p>";}
if(holidayHoursSunday[z]!=""&&holidayHoursSunday[z]!=undefined){popUpDisplay+="<p class='red'>Sun:"+holidayHoursSunday[z]+"</p>";}
popUpDisplay+="</div></div>";return function(){infowindow.setContent(popUpDisplay
+"<a href='"+ directStore+"?lat="
+ lat1[z]
+"&lng="
+ lng1[z]
+"&id="
+ id[z]
+"&name="
+ storeName1[z]
+"&address="
+ address1[z]
+"&phonenumber="
+ phonenumber1[z]
+"&hours="
+ phonenumber1[z]
+"&showmap=yes"
+"'>Directions to Store");infowindow.open(map,marker);if(linkHidden=='directStore'){$('.gm-style-iw a').remove();}}})(marker,z));}}}}
Big.STORE.Pagination={init:function(){var $itemsCount=$("#totalStores").val();Big.Pagination.init($itemsCount,10,true);}}
Big.STORE.goMapDirection={init:function(){$('.goMapDirection').live('click',function(e){e.preventDefault();var parentClass=$(this).parents('.row');$(parentClass).find('.mapDirection').submit();})
$('.dsnce-map').live('click',function(e){e.preventDefault();var parentClass=$(this).parents('.row');$(parentClass).find('.mapDirection').submit();})}}
Big.STORE.init=function(){Big.STORE.StatePicker();Big.STORE.getLatLong.init(false);Big.STORE.Pagination.init();Big.STORE.goMapDirection.init();Big.STORE.Cookies.init(true);}
$(document).ready(function(){Big.STORE.init();});